version: '3.1'

services:
  db:
    image: bf700010ce28
    environment:
      POSTGRES_PASSWORD: "passdb"
      POSTGRES_DB: "postgres"
    volumes:
      - "./assets/sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "5432:5432"